# site settings
title: Ben Fisher
subtitle: ""
email: ben.fisher@ed.ac.uk
description: "PhD Student in Marine Biogeochemistry <br> University of Edinburgh, UK"
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: "Grant Institiute, Kings Buildings, <br> University of Edinburgh"
city: Edinburgh
zip_code: EH9 3FE
country: "Scotland, UK"

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
googlescholar_url: https://scholar.google.com/citations?user=97WwFcQAAAAJ&hl=en
linkedin_url: https://uk.linkedin.com/in/ben-fisher-16a34b151
university_url: https://www.ed.ac.uk/profile/ben-fisher
twitter_url: https://twitter.com/BenFisher_

# build settings
markdown: kramdown

sass:
  style: compressed
